fixtures:
  symlinks:
    bitbucket: "#{source_dir}"
  repositories:
    archive:              "https://github.com/voxpupuli/puppet-archive.git"
    inifile:              "https://github.com/puppetlabs/puppetlabs-inifile.git"
    mysql_java_connector: "https://github.com/voxpupuli/puppet-mysql_java_connector.git"
    staging:              "https://github.com/voxpupuli/puppet-staging.git"
    stdlib:               "https://github.com/puppetlabs/puppetlabs-stdlib.git"
